"use strict";

const { Category } = require('../models');

const categoryData = [
    {},
    {},
    {},
    {},
    {},
    {babyAndKid: true,
bath: false,
clothing: false,
electronics: false,
furniture: false,
kitchenware: false,
other: true,
pet: false,
sporting: false,
toysAndGames: false},
    {babyAndKid: true,
bath: false,
clothing: false,
electronics: false,
furniture: false,
kitchenware: false,
other: true,
pet: false,
sporting: false,
toysAndGames: false},
    {babyAndKid: true,
bath: true,
clothing: false,
electronics: false,
furniture: false,
kitchenware: false,
other: true,
pet: true,
sporting: false,
toysAndGames: false},
    {babyAndKid: true,
bath: false,
clothing: false,
electronics: true,
furniture: false,
kitchenware: false,
other: true,
pet: false,
sporting: false,
toysAndGames: false},
    {babyAndKid: true,
bath: true,
clothing: false,
electronics: false,
furniture: false,
kitchenware: false,
other: true,
pet: false,
sporting: false,
toysAndGames: false},
    {},
    {},
    {},
    {},
    {}
];

const seedCategories = () => Category.bulkCreate(categoryData, { individualHooks: true });

module.exports = seedCategories;